### ISSUE TITLE
Improved README for Novice/First-Time Users

### ISSUE THREAD

**Issue by CraigCecilSSA** [SSAgov/genesys#30]
Be much more specific in all instructions (e.g., "to download, select the green Code button near the top of the page")

Be more explicit in the ordering of the README contents and instructions.

Add a link to the Tutorials index in the repo for direct access to this info.

**Comment by Ankkkyyyy** [comment]
Hey i have did some specific changes whatever i founded out,  give me review for sure.

**Comment by CraigCecilSSA** [comment]
Significant updates to the README, including an expanded Tutorials section.
